Files:
- From: /home/ashwin/Downloads
  To: /home/ashwin/tmp-rsync
  Flags:
  - '--recursive'
  - '--progress'
  - '--checksum'
  - '--owner'
  - '--group'
  Chown:
    Enabled: True
    User: 1001
    Group: 1001
